// ========== MAVEN COMMAND: Game Initialisation ==========

import type { GameState, GameUnit } from "@/lib/game-types";
import { WAVE_CONFIGS } from "@/lib/scenarios";

// Re-export for convenience
export { WAVE_CONFIGS } from "@/lib/scenarios";

// ---------------------------------------------------------------------------
// Player units
// ---------------------------------------------------------------------------

const playerFacilities: GameUnit[] = [
  {
    id: "base-tokyo",
    faction: "player",
    type: "vehicle",
    name: "東京司令部",
    lat: 35.6812,
    lng: 139.7671,
    hp: 100,
    maxHp: 100,
    attack: 10,
    defense: 80,
    speed: 0,
    status: "idle",
    detail: "首都中枢指揮施設 — 全方面統制",
    actedThisTurn: false,
  },
  {
    id: "base-osaka",
    faction: "player",
    type: "vehicle",
    name: "大阪防衛拠点",
    lat: 34.6937,
    lng: 135.5023,
    hp: 80,
    maxHp: 80,
    attack: 15,
    defense: 70,
    speed: 0,
    status: "idle",
    detail: "関西方面防衛統制所",
    actedThisTurn: false,
  },
  {
    id: "base-nagoya",
    faction: "player",
    type: "vehicle",
    name: "名古屋前線基地",
    lat: 35.1815,
    lng: 136.9066,
    hp: 80,
    maxHp: 80,
    attack: 15,
    defense: 70,
    speed: 0,
    status: "idle",
    detail: "中部前線作戦拠点",
    actedThisTurn: false,
  },
  {
    id: "base-fukuoka",
    faction: "player",
    type: "vehicle",
    name: "福岡哨戒基地",
    lat: 33.5904,
    lng: 130.4017,
    hp: 60,
    maxHp: 60,
    attack: 20,
    defense: 60,
    speed: 0,
    status: "idle",
    detail: "西方哨戒・早期警戒拠点",
    actedThisTurn: false,
  },
  {
    id: "base-sapporo",
    faction: "player",
    type: "vehicle",
    name: "札幌補給基地",
    lat: 43.0621,
    lng: 141.3544,
    hp: 60,
    maxHp: 60,
    attack: 10,
    defense: 60,
    speed: 0,
    status: "idle",
    detail: "北方補給・兵站支援拠点",
    actedThisTurn: false,
  },
];

const playerMobileUnits: GameUnit[] = [
  {
    id: "unit-cv-1",
    faction: "player",
    type: "vehicle",
    name: "機動戦闘車 Alpha",
    lat: 35.69,
    lng: 139.74,
    hp: 70,
    maxHp: 70,
    attack: 30,
    defense: 40,
    speed: 0.8,
    status: "idle",
    detail: "東京近郊待機 — 即応",
    actedThisTurn: false,
  },
  {
    id: "unit-cv-2",
    faction: "player",
    type: "vehicle",
    name: "機動戦闘車 Bravo",
    lat: 34.70,
    lng: 135.48,
    hp: 70,
    maxHp: 70,
    attack: 30,
    defense: 40,
    speed: 0.8,
    status: "idle",
    detail: "大阪近郊待機 — 即応",
    actedThisTurn: false,
  },
  {
    id: "unit-cv-3",
    faction: "player",
    type: "vehicle",
    name: "機動戦闘車 Charlie",
    lat: 35.20,
    lng: 136.88,
    hp: 70,
    maxHp: 70,
    attack: 30,
    defense: 40,
    speed: 0.8,
    status: "idle",
    detail: "名古屋近郊待機 — 即応",
    actedThisTurn: false,
  },
  {
    id: "unit-dr-1",
    faction: "player",
    type: "drone",
    name: "偵察ドローン Tokyo-1",
    lat: 35.70,
    lng: 139.80,
    hp: 30,
    maxHp: 30,
    attack: 15,
    defense: 10,
    speed: 1.4,
    status: "idle",
    detail: "東京湾岸哨戒任務",
    actedThisTurn: false,
  },
  {
    id: "unit-dr-2",
    faction: "player",
    type: "drone",
    name: "偵察ドローン Osaka-1",
    lat: 34.68,
    lng: 135.52,
    hp: 30,
    maxHp: 30,
    attack: 15,
    defense: 10,
    speed: 1.4,
    status: "idle",
    detail: "大阪湾哨戒任務",
    actedThisTurn: false,
  },
  {
    id: "unit-dr-3",
    faction: "player",
    type: "drone",
    name: "偵察ドローン Nagoya-1",
    lat: 35.16,
    lng: 136.94,
    hp: 30,
    maxHp: 30,
    attack: 15,
    defense: 10,
    speed: 1.4,
    status: "idle",
    detail: "伊勢湾哨戒任務",
    actedThisTurn: false,
  },
  {
    id: "unit-dr-4",
    faction: "player",
    type: "drone",
    name: "偵察ドローン Fukuoka-1",
    lat: 33.60,
    lng: 130.42,
    hp: 30,
    maxHp: 30,
    attack: 15,
    defense: 10,
    speed: 1.4,
    status: "idle",
    detail: "博多湾哨戒任務",
    actedThisTurn: false,
  },
  {
    id: "unit-sh-1",
    faction: "player",
    type: "ship",
    name: "護衛艦「あさぎり」",
    lat: 35.62,
    lng: 139.85,
    hp: 90,
    maxHp: 90,
    attack: 35,
    defense: 50,
    speed: 0.6,
    status: "idle",
    detail: "東京湾防衛配置",
    actedThisTurn: false,
  },
  {
    id: "unit-sh-2",
    faction: "player",
    type: "ship",
    name: "護衛艦「はかた」",
    lat: 33.58,
    lng: 130.38,
    hp: 90,
    maxHp: 90,
    attack: 35,
    defense: 50,
    speed: 0.6,
    status: "idle",
    detail: "福岡沖防衛配置",
    actedThisTurn: false,
  },
];

// ---------------------------------------------------------------------------
// Create initial game state
// ---------------------------------------------------------------------------

export function createInitialGameState(): GameState {
  return {
    phase: "briefing",
    wave: 1,
    turn: 0,
    maxTurns: WAVE_CONFIGS.reduce((sum, w) => sum + w.turns, 0),
    turnPhase: "player" as const,
    supply: 200,
    kpis: {
      combat: 100,
      supply: 100,
      morale: 100,
      intel: 80,
    },
    playerUnits: [...playerFacilities, ...playerMobileUnits],
    enemyUnits: [],
    events: [],
    missions: [],
    log: [
      {
        id: "log-init",
        role: "system",
        content: "MAVEN COMMAND システム起動 — 全接続確認完了",
        timestamp: "00:00",
        turn: 0,
      },
    ],
    selectedUnitId: null,
    selectedEventId: null,
  };
}
