// ========== MAVEN COMMAND: Game Initialisation ==========

import type { GameState, GameUnit, WaveConfig } from "@/lib/game-types";

// ---------------------------------------------------------------------------
// Player units
// ---------------------------------------------------------------------------

const playerFacilities: GameUnit[] = [
  {
    id: "base-tokyo",
    faction: "player",
    type: "vehicle",
    name: "東京司令部",
    lat: 35.6812,
    lng: 139.7671,
    hp: 100,
    maxHp: 100,
    attack: 10,
    defense: 80,
    speed: 0,
    status: "idle",
    detail: "首都中枢指揮施設 — 全方面統制",
  },
  {
    id: "base-osaka",
    faction: "player",
    type: "vehicle",
    name: "大阪防衛拠点",
    lat: 34.6937,
    lng: 135.5023,
    hp: 80,
    maxHp: 80,
    attack: 15,
    defense: 70,
    speed: 0,
    status: "idle",
    detail: "関西方面防衛統制所",
  },
  {
    id: "base-nagoya",
    faction: "player",
    type: "vehicle",
    name: "名古屋前線基地",
    lat: 35.1815,
    lng: 136.9066,
    hp: 80,
    maxHp: 80,
    attack: 15,
    defense: 70,
    speed: 0,
    status: "idle",
    detail: "中部前線作戦拠点",
  },
  {
    id: "base-fukuoka",
    faction: "player",
    type: "vehicle",
    name: "福岡哨戒基地",
    lat: 33.5904,
    lng: 130.4017,
    hp: 60,
    maxHp: 60,
    attack: 20,
    defense: 60,
    speed: 0,
    status: "idle",
    detail: "西方哨戒・早期警戒拠点",
  },
  {
    id: "base-sapporo",
    faction: "player",
    type: "vehicle",
    name: "札幌補給基地",
    lat: 43.0621,
    lng: 141.3544,
    hp: 60,
    maxHp: 60,
    attack: 10,
    defense: 60,
    speed: 0,
    status: "idle",
    detail: "北方補給・兵站支援拠点",
  },
];

const playerMobileUnits: GameUnit[] = [
  // --- Combat vehicles ---
  {
    id: "unit-cv-1",
    faction: "player",
    type: "vehicle",
    name: "機動戦闘車 Alpha",
    lat: 35.69,
    lng: 139.74,
    hp: 70,
    maxHp: 70,
    attack: 30,
    defense: 40,
    speed: 0.3,
    status: "idle",
    detail: "東京近郊待機 — 即応",
  },
  {
    id: "unit-cv-2",
    faction: "player",
    type: "vehicle",
    name: "機動戦闘車 Bravo",
    lat: 34.70,
    lng: 135.48,
    hp: 70,
    maxHp: 70,
    attack: 30,
    defense: 40,
    speed: 0.3,
    status: "idle",
    detail: "大阪近郊待機 — 即応",
  },
  {
    id: "unit-cv-3",
    faction: "player",
    type: "vehicle",
    name: "機動戦闘車 Charlie",
    lat: 35.20,
    lng: 136.88,
    hp: 70,
    maxHp: 70,
    attack: 30,
    defense: 40,
    speed: 0.3,
    status: "idle",
    detail: "名古屋近郊待機 — 即応",
  },
  // --- Patrol drones ---
  {
    id: "unit-dr-1",
    faction: "player",
    type: "drone",
    name: "偵察ドローン Tokyo-1",
    lat: 35.70,
    lng: 139.80,
    hp: 30,
    maxHp: 30,
    attack: 15,
    defense: 10,
    speed: 0.6,
    status: "idle",
    detail: "東京湾岸哨戒任務",
  },
  {
    id: "unit-dr-2",
    faction: "player",
    type: "drone",
    name: "偵察ドローン Osaka-1",
    lat: 34.68,
    lng: 135.52,
    hp: 30,
    maxHp: 30,
    attack: 15,
    defense: 10,
    speed: 0.6,
    status: "idle",
    detail: "大阪湾哨戒任務",
  },
  {
    id: "unit-dr-3",
    faction: "player",
    type: "drone",
    name: "偵察ドローン Nagoya-1",
    lat: 35.16,
    lng: 136.94,
    hp: 30,
    maxHp: 30,
    attack: 15,
    defense: 10,
    speed: 0.6,
    status: "idle",
    detail: "伊勢湾哨戒任務",
  },
  {
    id: "unit-dr-4",
    faction: "player",
    type: "drone",
    name: "偵察ドローン Fukuoka-1",
    lat: 33.60,
    lng: 130.42,
    hp: 30,
    maxHp: 30,
    attack: 15,
    defense: 10,
    speed: 0.6,
    status: "idle",
    detail: "博多湾哨戒任務",
  },
  // --- Naval ships ---
  {
    id: "unit-sh-1",
    faction: "player",
    type: "ship",
    name: "護衛艦「あさぎり」",
    lat: 35.62,
    lng: 139.85,
    hp: 90,
    maxHp: 90,
    attack: 35,
    defense: 50,
    speed: 0.2,
    status: "idle",
    detail: "東京湾防衛配置",
  },
  {
    id: "unit-sh-2",
    faction: "player",
    type: "ship",
    name: "護衛艦「はかた」",
    lat: 33.58,
    lng: 130.38,
    hp: 90,
    maxHp: 90,
    attack: 35,
    defense: 50,
    speed: 0.2,
    status: "idle",
    detail: "福岡沖防衛配置",
  },
];

// ---------------------------------------------------------------------------
// Wave definitions (1-5)
// ---------------------------------------------------------------------------

export const WAVE_CONFIGS: WaveConfig[] = [
  // ---- Wave 1: 偵察接触 ----
  {
    wave: 1,
    name: "偵察接触",
    description: "不明勢力の偵察ドローンが日本海側に出現",
    turns: 5,
    briefing:
      "司令、日本海側で不明な航空機が複数検出されました。偵察活動と推定されます。哨戒部隊を配置してください。",
    intel: [
      "レーダーに低高度目標を探知",
      "電子情報から偵察任務と判定",
    ],
    events: [
      {
        type: "recon",
        title: "不明ドローン接近",
        description: "日本海側から偵察ドローンが領空に接近中",
        severity: "warning",
        score: 40,
        location: "日本海沿岸",
        lat: 37.0,
        lng: 134.0,
        linkedUnitIds: [],
        suggestedAction: "哨戒ドローンによるインターセプト",
      },
      {
        type: "cyber",
        title: "通信妨害検知",
        description: "名古屋基地周辺で電波妨害を検出",
        severity: "info",
        score: 25,
        location: "名古屋前線基地",
        lat: 35.19,
        lng: 136.92,
        linkedUnitIds: [],
        suggestedAction: "通信バックアップ回線へ切替",
      },
    ],
    spawnUnits: [
      {
        faction: "enemy",
        type: "drone",
        name: "不明偵察ドローン A",
        lat: 37.5,
        lng: 133.5,
        hp: 20,
        maxHp: 20,
        attack: 5,
        defense: 5,
        speed: 0.5,
        detail: "低速偵察型 — 非武装",
        targetId: "base-nagoya",
      },
      {
        faction: "enemy",
        type: "drone",
        name: "不明偵察ドローン B",
        lat: 36.0,
        lng: 133.0,
        hp: 20,
        maxHp: 20,
        attack: 5,
        defense: 5,
        speed: 0.5,
        detail: "低速偵察型 — 非武装",
        targetId: "base-osaka",
      },
    ],
  },
  // ---- Wave 2: 沿岸威嚇 ----
  {
    wave: 2,
    name: "沿岸威嚇",
    description: "武装艦艇が九州北部に接近",
    turns: 6,
    briefing:
      "九州北方海域に武装艦艇群を確認。威嚇目的の可能性が高いですが、上陸準備の兆候もあります。海上部隊を展開してください。",
    intel: [
      "赤外線衛星で艦艇4隻を確認",
      "上陸用舟艇を搭載している模様",
    ],
    events: [
      {
        type: "attack",
        title: "武装艦艇接近",
        description: "九州北部沖に武装艦艇3隻が接近中",
        severity: "critical",
        score: 70,
        location: "福岡沖",
        lat: 34.0,
        lng: 130.0,
        linkedUnitIds: [],
        suggestedAction: "護衛艦を配置し警告射撃準備",
      },
      {
        type: "supply_cut",
        title: "海上輸送路脅威",
        description: "対馬海峡の民間航路に不明艦影",
        severity: "warning",
        score: 55,
        location: "対馬海峡",
        lat: 34.3,
        lng: 129.5,
        linkedUnitIds: [],
        suggestedAction: "民間船舶への航路警報発出",
      },
      {
        type: "recon",
        title: "電子偵察再開",
        description: "能登半島方面で電子偵察機を探知",
        severity: "info",
        score: 35,
        location: "能登半島沖",
        lat: 37.5,
        lng: 136.8,
        linkedUnitIds: [],
        suggestedAction: "電子戦装備の警戒態勢へ",
      },
    ],
    spawnUnits: [
      {
        faction: "enemy",
        type: "ship",
        name: "敵駆逐艦「影」",
        lat: 34.2,
        lng: 129.8,
        hp: 80,
        maxHp: 80,
        attack: 30,
        defense: 40,
        speed: 0.15,
        detail: "武装駆逐艦 — ミサイル装備",
      },
      {
        faction: "enemy",
        type: "ship",
        name: "敵輸送艦「霧」",
        lat: 34.0,
        lng: 129.5,
        hp: 60,
        maxHp: 60,
        attack: 10,
        defense: 30,
        speed: 0.1,
        detail: "上陸用舟艇搭載",
      },
    ],
  },
  // ---- Wave 3: 多方面攻撃 ----
  {
    wave: 3,
    name: "多方面攻撃",
    description: "同時多発的なサイバー攻撃と物理攻撃",
    turns: 7,
    briefing:
      "司令、事態は深刻です。複数方面からの同時攻撃を確認。サイバー攻撃で通信網が部分的に遮断されています。全部隊を戦闘態勢に移行してください。",
    intel: [
      "サイバー攻撃のソースを特定中",
      "太平洋側にも潜水艦の反応あり",
      "航空機の接近を複数方向から探知",
    ],
    events: [
      {
        type: "cyber",
        title: "大規模サイバー攻撃",
        description: "東京司令部のネットワークにDDoS攻撃 — 一部系統ダウン",
        severity: "critical",
        score: 85,
        location: "東京司令部",
        lat: 35.68,
        lng: 139.77,
        linkedUnitIds: [],
        suggestedAction: "サイバー防衛チーム即時投入",
      },
      {
        type: "attack",
        title: "航空攻撃警報",
        description: "太平洋側から不明航空機編隊が接近",
        severity: "critical",
        score: 80,
        location: "太平洋沿岸",
        lat: 34.5,
        lng: 138.0,
        linkedUnitIds: [],
        suggestedAction: "迎撃部隊をスクランブル発進",
      },
      {
        type: "sabotage",
        title: "補給線破壊工作",
        description: "大阪〜名古屋間の補給路でIED発見",
        severity: "warning",
        score: 60,
        location: "東海道",
        lat: 34.95,
        lng: 136.2,
        linkedUnitIds: [],
        suggestedAction: "工兵部隊による処理と迂回路確保",
      },
    ],
    spawnUnits: [
      {
        faction: "enemy",
        type: "drone",
        name: "攻撃ドローン編隊 X",
        lat: 34.2,
        lng: 137.5,
        hp: 40,
        maxHp: 40,
        attack: 25,
        defense: 15,
        speed: 0.45,
        detail: "武装ドローン群 — 対地攻撃",
      },
      {
        faction: "enemy",
        type: "vehicle",
        name: "浸透工作車両",
        lat: 35.0,
        lng: 136.0,
        hp: 50,
        maxHp: 50,
        attack: 20,
        defense: 25,
        speed: 0.25,
        detail: "破壊工作用 — IED搭載",
      },
      {
        faction: "enemy",
        type: "cyber",
        name: "サイバー攻撃ノード C",
        lat: 35.68,
        lng: 139.77,
        hp: 30,
        maxHp: 30,
        attack: 15,
        defense: 5,
        speed: 0,
        detail: "DDoS発生源 — 仮想ノード",
      },
    ],
  },
  // ---- Wave 4: 全面侵攻 ----
  {
    wave: 4,
    name: "全面侵攻",
    description: "本格的な上陸作戦が開始される",
    turns: 8,
    briefing:
      "全面侵攻が開始されました。九州北部への上陸作戦と、関東への航空攻撃が同時進行中。全戦力を投入し、拠点を死守してください。",
    intel: [
      "上陸部隊が福岡沿岸に接近",
      "東京湾に敵潜水艦の存在を確認",
      "札幌方面にも長距離ミサイルの脅威",
    ],
    events: [
      {
        type: "attack",
        title: "九州上陸作戦",
        description: "福岡沿岸に大規模上陸部隊が接近中",
        severity: "critical",
        score: 92,
        location: "福岡沿岸",
        lat: 33.62,
        lng: 130.35,
        linkedUnitIds: [],
        suggestedAction: "全沿岸防衛部隊を配置・砲撃準備",
      },
      {
        type: "attack",
        title: "東京湾潜水艦",
        description: "東京湾口に敵潜水艦を探知 — ミサイル発射態勢の可能性",
        severity: "critical",
        score: 88,
        location: "東京湾口",
        lat: 35.3,
        lng: 139.8,
        linkedUnitIds: [],
        suggestedAction: "対潜哨戒を最優先で実施",
      },
      {
        type: "supply_cut",
        title: "北海道補給路遮断",
        description: "札幌基地への補給航路が妨害されている",
        severity: "warning",
        score: 65,
        location: "津軽海峡",
        lat: 41.5,
        lng: 140.5,
        linkedUnitIds: [],
        suggestedAction: "空路補給に切り替え",
      },
      {
        type: "sabotage",
        title: "後方攪乱",
        description: "大阪拠点周辺で不審車両を複数確認",
        severity: "warning",
        score: 55,
        location: "大阪近郊",
        lat: 34.72,
        lng: 135.50,
        linkedUnitIds: [],
        suggestedAction: "警戒態勢強化・検問実施",
      },
    ],
    spawnUnits: [
      {
        faction: "enemy",
        type: "ship",
        name: "敵強襲揚陸艦「嵐」",
        lat: 33.8,
        lng: 130.0,
        hp: 100,
        maxHp: 100,
        attack: 35,
        defense: 50,
        speed: 0.1,
        detail: "大型揚陸艦 — 歩兵部隊搭載",
      },
      {
        faction: "enemy",
        type: "infantry",
        name: "敵上陸部隊 第1波",
        lat: 33.7,
        lng: 130.2,
        hp: 60,
        maxHp: 60,
        attack: 25,
        defense: 30,
        speed: 0.2,
        detail: "精鋭歩兵 — 上陸作戦中",
      },
      {
        faction: "enemy",
        type: "ship",
        name: "敵潜水艦「深淵」",
        lat: 35.1,
        lng: 140.0,
        hp: 70,
        maxHp: 70,
        attack: 40,
        defense: 35,
        speed: 0.12,
        detail: "巡航ミサイル搭載潜水艦",
      },
      {
        faction: "enemy",
        type: "vehicle",
        name: "敵工作部隊 B",
        lat: 34.80,
        lng: 135.55,
        hp: 40,
        maxHp: 40,
        attack: 20,
        defense: 20,
        speed: 0.3,
        detail: "後方撹乱部隊",
      },
    ],
  },
  // ---- Wave 5: 最終決戦 (Boss) ----
  {
    wave: 5,
    name: "最終決戦",
    description: "敵旗艦が出現 — 決戦の時",
    turns: 10,
    briefing:
      "司令、敵旗艦を確認しました。これが最後の戦いです。全残存戦力を集結させ、敵の中枢を叩いてください。勝利はもう目前です。",
    intel: [
      "敵旗艦は重装甲・高火力 — 集中攻撃が必要",
      "残存敵部隊が旗艦護衛に合流中",
      "勝利条件: 敵旗艦の撃沈",
    ],
    events: [
      {
        type: "boss",
        title: "敵旗艦出現",
        description: "超大型戦闘艦が太平洋側から接近 — 全艦隊を指揮している",
        severity: "critical",
        score: 100,
        location: "太平洋",
        lat: 33.0,
        lng: 137.0,
        linkedUnitIds: [],
        suggestedAction: "全戦力を集中し迎撃せよ",
      },
      {
        type: "attack",
        title: "最終航空波状攻撃",
        description: "残存航空戦力による大規模攻撃",
        severity: "critical",
        score: 85,
        location: "関東上空",
        lat: 35.5,
        lng: 139.5,
        linkedUnitIds: [],
        suggestedAction: "防空網を最大展開",
      },
      {
        type: "cyber",
        title: "最終サイバー攻撃",
        description: "全拠点のシステムに同時攻撃",
        severity: "warning",
        score: 70,
        location: "全拠点",
        lat: 35.68,
        lng: 139.77,
        linkedUnitIds: [],
        suggestedAction: "バックアップ系統で運用継続",
      },
    ],
    spawnUnits: [
      {
        faction: "enemy",
        type: "ship",
        name: "敵旗艦「天鬼」",
        lat: 32.5,
        lng: 136.5,
        hp: 200,
        maxHp: 200,
        attack: 50,
        defense: 60,
        speed: 0.08,
        detail: "超重装甲旗艦 — 全軍の中枢",
      },
      {
        faction: "enemy",
        type: "drone",
        name: "護衛ドローン群",
        lat: 32.8,
        lng: 136.8,
        hp: 50,
        maxHp: 50,
        attack: 20,
        defense: 15,
        speed: 0.4,
        detail: "旗艦護衛用武装ドローン",
      },
      {
        faction: "enemy",
        type: "ship",
        name: "敵護衛艦「鬼火」",
        lat: 33.2,
        lng: 137.2,
        hp: 70,
        maxHp: 70,
        attack: 30,
        defense: 40,
        speed: 0.12,
        detail: "旗艦直衛艦",
      },
    ],
  },
];

// ---------------------------------------------------------------------------
// Create initial game state
// ---------------------------------------------------------------------------

export function createInitialGameState(): GameState {
  return {
    phase: "briefing",
    wave: 1,
    turn: 0,
    maxTurns: WAVE_CONFIGS.reduce((sum, w) => sum + w.turns, 0),
    kpis: {
      combat: 100,
      supply: 100,
      morale: 100,
      intel: 80,
    },
    playerUnits: [...playerFacilities, ...playerMobileUnits],
    enemyUnits: [],
    events: [],
    missions: [],
    log: [
      {
        id: "log-init",
        role: "system",
        content: "MAVEN COMMAND システム起動 — 全接続確認完了",
        timestamp: new Date().toISOString(),
        turn: 0,
      },
    ],
    selectedUnitId: null,
    selectedEventId: null,
  };
}
